---
name: "test build"

on:
  pull_request:
  push:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - if: ${{ matrix.os == 'windows-latest' }}
        run: choco install -y openssl --version 1.1.1.1700      
      - run: nimble build -y
